namespace: lancom
name: swoslx
version: 0.1.0
readme: README.md
authors:
  - Heiko Tropartz (github.com/ButAry)
description: Ansible Collection for LANCOM SWOSLX devices.
license_file: LICENSE
tags:
  - lancom
  - swoslx
  - networking
repository: https://github.com/ButAry/ansible-lancom-swoslx
homepage: https://github.com/ButAry/ansible-lancom-swoslx
issues: https://github.com/ButAry/ansible-lancom-swoslx/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
dependencies:
    "ansible.netcommon": "=7.2.0"
